In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("../data.csv")
df.head()

,Unnamed: 0,DISTRICT_NUMBER,DISTRICT,CAMPUS_NUMBER,CAMPUS,REGION,COUNTY,SCHOOL_TYPE,GRADES_SERVED,CHARTER,...,RACE_BLACK_OR_AFRICAN_AMERICAN,RACE_HISPANIC/LATINO,RACE_NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER,RACE_TWO_OR_MORE_RACES,RACE_WHITE,TEACHERS_COUNT,LAT,LONG,MEDIAN_HOUSEHOLD_INCOME_AREA,ST_SCHID
0,0,1902,CAYUGA ISD,1902001.0,CAYUGA H S,REGION 07: KILGORE,ANDERSON,High School,09 - 12,No,...,12.0,36.0,0.0,16.0,276.0,19.34,31.9569,-95.9744,72483.0,TX-001902-001902001
1,1,1902,CAYUGA ISD,1902041.0,CAYUGA MIDDLE,REGION 07: KILGORE,ANDERSON,Middle School,06 - 08,No,...,16.0,32.0,0.0,18.0,264.0,11.20,31.9569,-95.9744,72483.0,TX-001902-001902041
2,2,1902,CAYUGA ISD,1902103.0,CAYUGA EL,REGION 07: KILGORE,ANDERSON,Elementary,PK - 05,No,...,28.0,44.0,0.0,20.0,420.0,17.86,31.9569,-95.9744,72483.0,TX-001902-001902103
3,3,1903,ELKHART ISD,1903001.0,ELKHART H S,REGION 07: KILGORE,ANDERSON,High School,09 - 12,No,...,24.0,76.0,2.0,20.0,502.0,35.72,31.6275,-95.5785,76397.0,TX-001903-001903001
4,4,1903,ELKHART ISD,1903041.0,ELKHART MIDDLE,REGION 07: KILGORE,ANDERSON,Middle School,06 - 08,No,...,18.0,62.0,0.0,16.0,442.0,23.82,31.6279,-95.5780,76397.0,TX-001903-001903041

In [17]:
salaries = pd.read_csv("./salaries.csv")
salaries = salaries[salaries["Staff_Category"] == "TEACHING STAFF"]
salaries = salaries[salaries["Staff"] == "TOTAL TEACHING STAFF"]
salaries = salaries[["District", "Average Base Pay"]]
salaries = salaries.rename(columns={"District": "DISTRICT_NUMBER", "Average Base Pay": "AVG_TEACHER_SALARY"})
salaries.head()

     DISTRICT_NUMBER  AVG_TEACHER_SALARY
15             57816               51912
60             57829               62482
109           101871               64047
137           109901               54155
169            95901               51462

In [18]:
merged = pd.merge(df, salaries, on="DISTRICT_NUMBER", how="left")
merged.head()

,Unnamed: 0,DISTRICT_NUMBER,DISTRICT,CAMPUS_NUMBER,CAMPUS,REGION,COUNTY,SCHOOL_TYPE,GRADES_SERVED,CHARTER,...,RACE_HISPANIC/LATINO,RACE_NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER,RACE_TWO_OR_MORE_RACES,RACE_WHITE,TEACHERS_COUNT,LAT,LONG,MEDIAN_HOUSEHOLD_INCOME_AREA,ST_SCHID,AVG_TEACHER_SALARY
0,0,1902,CAYUGA ISD,1902001.0,CAYUGA H S,REGION 07: KILGORE,ANDERSON,High School,09 - 12,No,...,36.0,0.0,16.0,276.0,19.34,31.9569,-95.9744,72483.0,TX-001902-001902001,55570.0
1,1,1902,CAYUGA ISD,1902041.0,CAYUGA MIDDLE,REGION 07: KILGORE,ANDERSON,Middle School,06 - 08,No,...,32.0,0.0,18.0,264.0,11.20,31.9569,-95.9744,72483.0,TX-001902-001902041,55570.0
2,2,1902,CAYUGA ISD,1902103.0,CAYUGA EL,REGION 07: KILGORE,ANDERSON,Elementary,PK - 05,No,...,44.0,0.0,20.0,420.0,17.86,31.9569,-95.9744,72483.0,TX-001902-001902103,55570.0
3,3,1903,ELKHART ISD,1903001.0,ELKHART H S,REGION 07: KILGORE,ANDERSON,High School,09 - 12,No,...,76.0,2.0,20.0,502.0,35.72,31.6275,-95.5785,76397.0,TX-001903-001903001,47916.0
4,4,1903,ELKHART ISD,1903041.0,ELKHART MIDDLE,REGION 07: KILGORE,ANDERSON,Middle School,06 - 08,No,...,62.0,0.0,16.0,442.0,23.82,31.6279,-95.5780,76397.0,TX-001903-001903041,47916.0

In [20]:
merged.to_csv("../data_teacher_salaries.csv")